version: '3.8'
services:
  worker1:
    image: elisiomualumene/worker:latest
    hostname: worker1
    depends_on:
      - postgres
    networks:
      - worker_bridge
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  worker2:
    image: elisiomualumene/worker:latest
    hostname: worker2
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    networks:
      - worker_bridge
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - worker1
      - worker2
    ports:
      - "8080:80"
    networks:
      - worker_bridge
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    networks:
      - worker_bridge
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

volumes:
  pgdata:
    driver: local

networks:
  worker_bridge:
    driver: bridge